steps:
  - id: deploy-frontend
    name: gcr.io/cloud-builders/npm
    entrypoint: "bash"
    dir: react-frontend
    args:
      - "-c"
      - "make deploy"
  - id: deploy-api
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    dir: api
    args:
      - "-c"
      - "make deploy"
