steps:
  - id: install
    name: golang:1.16.6-buster
    dir: api
    args: ['make', 'install']

  - id: lint
    name: golang:1.16.6-buster
    dir: api
    waitFor: ["install"]
    args: ['make', 'lint']

  - id: test
    name: golang:1.16.6-buster
    dir: api
    waitFor: ["install"]
    args: ['make', 'test']
