steps:
  - id: lint
    name: golang:1.16.6-buster
    dir: rpi
    waitFor: ["-"]
    args: ['make', 'lint']

  - id: test
    name: golang:1.16.6-buster
    dir: rpi
    waitFor: ["-"]
    args: ['make', 'test']

  - id: build
    name: golang:1.16.6-buster
    dir: rpi
    waitFor: ["-"]
    args: ['make', 'build']
